jobs:
  - name: Report_UserandProject_Delete
    conf:
      spark.cassandra.connection.host: CASSANDRAIP
      spark.cassandra.auth.username: CASSANDRA_USER
      spark.cassandra.auth.password: CASSANDRA_PASS

    extract:

      - format: org.apache.spark.sql.cassandra
        options:
          keyspace: CASSANDRA_KEYSPACE
          table: report_project

      - format: org.apache.spark.sql.cassandra
        options:
          keyspace: CASSANDRA_KEYSPACE
          table: report_user
        target: reportuser

    transform:

      - filterExpression:
          expression: created_date  < 'ETL_TIMESTAMP2'

      - filterExpression:
          expression: is_test_org='FALSE' and org_profile='RESELLER'
        source: reportuser

    load:
      - format: org.apache.spark.sql.cassandra
        mode: Delete
        options:
          keyspace: CASSANDRA_KEYSPACE
          table: report_project

      - format: org.apache.spark.sql.cassandra
        mode: Delete
        options:
          keyspace: CASSANDRA_KEYSPACE
          table: report_user
        source: reportuser
